

public class LcsString {
	public static void main(String[] args) {
		String s = "abcdefghijklmnolpeodihigonocopmoeadsfadfweakdhgfaksdfweuifgasefrbwaelrfagsedflakjsdfasd";
		int h = s.hashCode();
		String p = "abc";
		String t = "abcdefghijklmnolpeodihigonocopmoeadsfadfweakdhgfaksdfweuifgasefrbwaelrfagsedflakjsdfasdfasdfalsdfgasdlkfgasdlfgakadgfasdfiuawerfbwsaeufgasdlfjkasdfadfaldsfadifgwerfejawiuewalraelrawelgrfasdfakjdfladgfiwuebrfweuraleuqalweafdaiugadlfgadlfiugawelfaalgaflugaelnfavcauszsfweiasdfweadsfweiutrawbamsdfagiwefadfaedfapueawadyadwebzsweugsdfasdfuawefbasdfuigawefaokadoiuwebuiadigaeibiuweiaugadbaiuegiaedbfiuadsgfiuageifbwaiebfuaookadkoaedfoiaweyuoaebaisdfaigsefadgfawebfuiadgfiagefbaiegfadfabsefuwefaokadoiuwebuiadigaeibiuweiaugadbaiuegiaedbfiuadsgfiuageifbwaiebfuaookadkoaedfoiaweyuoaebaisdfaigaksdfweuifgasefrbwaelrfagsedflakjsdfasdfasdfalsdfgasdlkfgasdlfgakadgfasdfiuawerfbwsaeufgasdlfjkasdfadfaldsfadifgwerfejawiuewalraelrawelgrfasdfakjdfladgfiwuebrfweuraleuqalweafdaiugadlfgadlfiugawelfaalgaflugaelnfavcauszsfweiasdfweadsfweiutrawbamsdfagiwefadfaedfapueawadyadwebzsweugsdfasdfuawefbasdfuigawefaokadoiuwebuiadigaeibiuweiaugadbaiuegiaedbfiuadsgfiuageifbwaiebfuaookadkoaedfoiaweyuoaebaisdfaigsefadgfawebfui";
		t.hashCode();
		System.out.println(s.hashCode());
	}
}